# set active env
spring:
  profiles:
    active: dev
  datasource:
    url: ${datasource.url}
    driver-class-name: ${datasource.driver}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      
# set server
server:
  servlet:
    context-path: /zdemo-springboot